baseurl = "http://docs.flassh.co/"
languageCode = "en-us"
title = "Flassh Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Digitalcraftsman"
	# description = "A material design theme for documentations."
	copyright = "Flassh"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	# version = "1.0.0"
	# logo = "images/logo.png"
	# favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
  	primary = "grey"
  	accent  = "blue"

  [params.font]
    text = "Roboto"
    code = "Roboto Mono"

[social]
	twitter = "flasshco"
	# github  = "flassh"

[[menu.main]]
	name   = "Getting Started"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Flassh Booth (Windows)"
	url    = "booth/"
	weight = 10

[[menu.main]]
	name   = "Flassh iOS"
	url    = "ios/"
	weight = 20

[[menu.main]]
	name   = "Web Galleries / Admin"
	url    = "web/"
	weight = 30


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
